### PR TITLE
Implement tweet cards

### PR DESCRIPTION
**Pull request by V1shvesh**

### CODE REVIEW

**Comment by ryzokuken** [comment]
@V1shvesh is this ready to be merged?

**Comment by ryzokuken** [comment]
@V1shvesh Could you also add a screenshot or two in the README in this (or another) PR?

**Comment by V1shvesh** [comment]
Take a look now

**Comment by V1shvesh** [comment]
Oh.. wait

**Comment by ryzokuken** [comment]
Looks great! Merging this.

**Pull request merged**
